### ISSUE TITLE
Variable in for loop is a String

### ISSUE THREAD

**Issue by rainermueller** [markocupic/contao-news-infinite-scroll-bundle#10]
We upgraded from 1.0.5 to 1.3.4 version, the infinite scroll stopped working.

The `idLast` variable in `news_infinite_scroll.js` is of type String.

```
                // Generate all urls from first to last
                for (i = idNext; i <= idLast; i++) {
                    let url = hrefNext.replace(regexpNext, 'page_n' + idModule + '=' + i);
                    _arrUrls.push(url);
                }
```

e.g. `idNext = 2` and `idLast = 17` will not push any URL to `_arrUrls`. Using `parseInt` function solves the issue.

As workaround we need to restrict the number of pagination links.

Gesamtzahl der Beiträge - 25 (instead of 0)
Elemente pro Seite - 5

**Comment by markocupic** [comment]
Schau mir das heute mal an. Lustigerweise funktioniert die Extension [hier](https://www.sac-pilatus.ch/publikationen.html#newslistInfiniteScroll_343).
