### ISSUE TITLE
ReferenceError: ContaoNewsInfiniteScroll isn't defined

### ISSUE THREAD

**Issue by operatorone** [markocupic/contao-news-infinite-scroll-bundle#12]
Habe die Erweiterung in einer Contao 4.9.22 Installation laufen und erhalte auf allen Seiten, außer auf der News-Listen-Seite folgende Fehlermeldung:
`jQuery.Deferred exception: ContaoNewsInfiniteScroll is not defined ReferenceError: ContaoNewsInfiniteScroll is not defined`

`Uncaught ReferenceError: ContaoNewsInfiniteScroll is not defined`

Kann man es ggf. so regeln, dass Skript nur auf der Seite mit dem News-Listen-Modul eingebunden wird?

**Comment by markocupic** [comment]
Hm... die Frage ist, wer ist "man"? ;-)

**Comment by operatorone** [comment]
Könntest "du" die Ausgabe des Skripts auf die Seiten auf der das Modul platziert ist einschränken? Würde ja auch den Ladezeiten der Seite allgemein zuträglich sein 😉

**Comment by markocupic** [comment]
Hi again
You could make a pull request and thus contribute to the project. If that is not possible, you can get in touch with the author and have it implemented as part of a small order.

Open source doesn't mean someone sit down and work for you. I hope you can understand my point of view.

K.R. Marko

**Comment by operatorone** [comment]
Nobody expects anyone to work for free. Since I can't make the adjustment myself, it would be a good idea to just submit an offer, what this effort could mean. If it's a reasonable amount, there's no problem to get this done, so the community and Contao also has a benefit of it.

**Comment by markocupic** [comment]
Hi Tilman
This isn't a big issue. Can you send me your email address? You'll find mine in the header of each file of the application.
Cheers
