### ISSUE TITLE
Modul für Newsarchiv

### ISSUE THREAD

**Issue by fr4nk2342** [markocupic/contao-news-infinite-scroll-bundle#13]
Super Extension! Lässt sich das auch für das Contao-News-Archiv verwenden? Dazu bräuchte es einen neuen Modultyp für das Archiv, da die Newsliste nicht nach gewählten Monat/Jahr filtert.

**Comment by markocupic** [comment]
Hi Frank
Not until now, but feel free to add a pull request.

**Comment by 0xfrnk** [comment]
OK, let's see if I can get something done. A good time to take a closer look at module development.
