### ISSUE TITLE
Verwendung mit Catalog-Manager

### ISSUE THREAD

**Issue by Fanni-Portier** [markocupic/contao-news-infinite-scroll-bundle#15]
Hallo!

Kann man dieses Paket auch mit im Catalog-Manager erstellten Modulen verwenden?
https://github.com/alnv/catalog-manager

**Comment by markocupic** [comment]
Hallo @Fanni-Portier 
Nein, das geht nicht. 
Liebe Grüsse 
MC

**Comment by Fanni-Portier** [comment]
Sehr schade - danke für die Info.
