### ISSUE TITLE
Error: Could not find template

### ISSUE THREAD

**Issue by GMTeams** [markocupic/contao-news-infinite-scroll-bundle#17]
Contao 4.13.38
Contao-news-infinite-scroll-bundle: 1.4.2
PHP 8.1.27

I was updating Contao-news-infinite-scroll-bundle from 1.4.1 to 1.4.2 and now on all frontend pages there is an error.
Logfile says:
`request.CRITICAL: Uncaught PHP Exception Exception: "Could not find template "j_news_infinite_scroll"" at /homepages/19/123/htdocs/_dev/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php line 156 {"exception":"[object] (Exception(code: 0): Could not find template \"j_news_infinite_scroll\" at /homepages/19/123/htdocs/_dev/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:156)"} []`

I have switched back to 1.4.1 and the error is gone.
Thank you.

**Comment by markocupic** [comment]
@GMTeams Are you using a custom template js_news_infinite_scroll in your layout? You have probably set the wrong file name. 
The file name is not "j_news_infinite_scroll", but "js_news_infinite_scroll".

**Comment by GMTeams** [comment]
Okay thanks, but I'm not using a custom template js_news_infinite_scroll or j_news_infinite_scroll.

Only thing which catches my attention is in the page layout, there is a jQuery Template "j_news_infinite_scroll" connected.
I want to point out that this is not named as "js_news_infinite_scroll" but this should not be the problem.

But now I know the problem is the reference to this wrong (old) file name, with this information I can further investigate this in my system. Maybe there is a reference somewhere which has to be updated. 

Thank you.

**Comment by rainermueller** [comment]
We have the same issue with 1.4.1 to 1.4.2 upgrade. There is no layout template used.

Reverted back to 1.4.1 works again.

**Comment by rabauss** [comment]
I think the problem is that version 1.4.2 is based on 2.x - so semantic versioning is not correct!

**Comment by markocupic** [comment]
@rabauss @rainermueller @GMTeams Perhaps this is the cause. I've renamed the branch to 1.x. Does the error still occurs?

**Comment by rainermueller** [comment]
>Version 1.4.2 / 1.4.3 shows no errors in /var/logs or browser console, but pagination is not replaced with infinite scroll.
@rainermueller Contao version?

**Comment by rabauss** [comment]
As long as the changes from last year are included in ``1.x`` only the renaming won't solve the problem.
see: https://github.com/markocupic/contao-news-infinite-scroll-bundle/compare/1.4.1...1.4.3

The ``1.x`` has to be copied as ``2.x``
Then the ``1.x`` has to be reset to ``1.4.1`` and the last changes from 2024 should be cherry-picked from ``2.x`` - afterwards new tag has to be set on ``1.x``
