### ISSUE TITLE
js_highlight

### ISSUE THREAD

**Issue by hinzke** [markocupic/contao-news-infinite-scroll-bundle#6]
Wenn man js_highlight im Layout nutzt, lädt es beim nachladen der liste nicht mit.

Also die zuerst geladenen werden vernünftig generiert. Und alle weiteren nicht mehr nach dem loadmore

**Comment by markocupic** [comment]
Hallo @hinzke
Ohne das jetzt genau studiert zu haben. Aber ich denke, du könntest das wie folgt lösen.
Im Template (j_news_infinite_scroll.html5) in Zeile 80 gibt es die Möglichkeit auf das Nachladen von Inhalt zu reagieren. 

https://github.com/markocupic/contao-news-infinite-scroll-bundle/blob/59eba56fa4d5c7737a65f1078008dc8687bbb04f/src/Resources/contao/templates/jquery/j_news_infinite_scroll.html5#L75-L81 

Guck auch [hier](https://laracasts.com/discuss/channels/general-discussion/how-to-use-highlightjs-with-laravel-53-and-vue):
![Unbenannt](https://user-images.githubusercontent.com/1525166/84313065-4a501e80-ab66-11ea-8132-22027943e824.JPG)

**Comment by hinzke** [comment]
danke hat funktioniert

`                onAppendCallback: function (instance) {
                    // Do some actions
                hljs.initHighlighting.called = false;
                hljs.initHighlighting();
                }`
