### ISSUE TITLE
Error in bundle extension

### ISSUE THREAD

**Issue by fritzmg** [markocupic/contao-news-infinite-scroll-bundle#9]
Version `1.3.2` causes the following error currently:

```
Users will expect the alias of the default extension of a bundle to be the underscored version of the bundle name ("markocupic_contao_news_infinite_scroll"). You can override "Bundle::getContainerExtension()"   
   if you want to use "marko_cupic_contao_news_infinite_scroll" or another alias.
```

This is because the bundle extension has a non-standard name. Currently it is named

```
Markocupic\ContaoNewsInfiniteScrollBundle\DependencyInjection\MarkoCupicContaoNewsInfiniteScrollExtension
```

but the name needs to be

```
Markocupic\ContaoNewsInfiniteScrollBundle\DependencyInjection\MarkocupicContaoNewsInfiniteScrollExtension
```

i.e. lower case `c` in `Markocupic` - because your vendor namespace is `Markocupic` and not `MarkoCupic`.

So you need to:

1. Rename `src/DependencyInjection/MarkoCupicContaoNewsInfiniteScrollExtension.php` to `src/DependencyInjection/MarkocupicContaoNewsInfiniteScrollExtension.php`
2. Change `class MarkoCupicContaoNewsInfiniteScrollExtension` to `class MarkocupicContaoNewsInfiniteScrollExtension`

**Comment by markocupic** [comment]
War wohl ein Flüchtigkeitsfehler, danke dir.
Fixed in e145b1cabfe7813998fe8ced6d4cb2e333a0d49a
